### ISSUE TITLE
Possible bug in PHP implementation of caml_update_dummy?

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/rehp#40]
The implementation for PHP does:
```
  for ($i = 0; $i < C\count($y); $i++) {
    $x[] = $y[$i];
  }
```
But the JS version does:
```javascript
  var i = y.length; while (i--) x[i] = y[i]; return 0;
```

not pushing them onto the end but clobbering. In practice `x` is often an EStruct with a single zero item.

**Comment by jordwalke** [comment]
Relevant commit that I landed a long time ago which changes the `caml_alloc_dummy` in generate.ml:
```
commit cec840973a22dfc3feb6838e0fd5e0c400f1bc1b
Author: Jordan Walke <jordojw@gmail.com>
Date:   Fri Apr 10 03:43:21 2020 -0700

    Make caml_alloc_dummy inline empty elements so that we can use fixed Vectors for updating dummies
```

**Comment by Lupus** [comment]
Relevant discussion (happened today) from discord (ocaml #general)


**Lupus**
@jordwalke  and I have a question regarding caml_alloc_dummy
this primitive is emitted by OCaml as part of recursive let binding transformation and is ought to allocate a dummy cell which will be later updated
caml_alloc_dummy receives the size of required block
js_of_ocaml represents OCaml values as arrays
js_ofocaml is currently ignoring the size, relying on javascript semantics for array updates to actually extend the array if it's smaller than required, and thus it just allocates empty array to represent dummy updateable block of universal size
in rehp we wanted to allocate exactly the required size to avoid requirement for javascript semantics on dynamic array growth
we observe that dummy cell is allocated with size 1, making it EStruct(0), and is later updated with `ETag(0, ETag(0, f, a)), which is effectively EStruct(0, EStruct(0, f, a_))` as in jsoo memory model tags are encoded as first element of the resulting array (not sure this is the same for OCaml native memory model)
obvious solution seems to increase the requrested size by one to accomodate for potential tag, but if there will be no tag, we will have extra element, which won't hurt much unless length of this block will be requested later
any ideas on this matter are much appreciated!
cc @hhugo

**ggole**
The native OCaml representation stores tags as a byte-sized field in the object header
I don't think that anything is actually left untagged

**joris**
did 4.09 support got dropped from git version of ocamllsp ?

**Lupus**
> I don't think that anything is actually left untagged

@ggole how can one possibly confirm that?

**ggole**
You can sort of deduce it from the existence of operations like Obj.tag
And descriptions of the OCaml representation in general

**octachron**
Note that integer-like value are untagged.
And floats in float-only records or arrays

**hhugo**
'we observe that dummy cell is allocated with size 1, making it Estruct(0)', the size doesn't take into account the header / tag, I believe you should instead generate 'estruct(0,dummyvalue)'

**ggole**
Yeah, I meant blocks in particular

**Lupus**
so we should generate an array of requested size plus one to accomodate for tag in implementation of caml_alloc_dummy @hhugo ?

> Note that integer-like value are untagged.
> And floats in float-only records or arrays

makes sense

**hhugo**
I think so yes
Look at the implementation of caml_obj_block
@Lupus  ^^

**Lupus**
when is caml_obj_block used?
and you mean look it up in jsoo or ocaml itself?

```js
//Provides: caml_obj_block const (const,const)
function caml_obj_block (tag, size) {
  var o = new Array(size+1);
  o[0]=tag;
  for (var i = 1; i <= size; i++) o[i] = 0;
  return o;
}
```

probably you mean this code, which does exactly what is needed in case of caml_alloc_dummy?
(well, aside of assigning some dummy tag 0 instead of expecting some from elsewhere, worst case scenario this block will look like an empty list in this case)

**hhugo**
:thumbsup:
